---
exclude_paths:
  - "node_modules/**"
  - "doc/**"
  - ".context/**"
  - "e2e/**"
  - "dist/**"
  - "coverage/**"
  - "data/**"
  - "uploads/**"

engines:
  eslint:
    enabled: false
  pmd:
    enabled: false
  pmd-legacy:
    enabled: false
