---
exclude_paths:
  - "node_modules/**"
  - "doc/**"
  - ".context/**"
  - "e2e/**"
  - "dist/**"
  - "coverage/**"
  - "data/**"
  - "uploads/**"

engines:
  eslint:
    exclude_paths:
      - "packages/frontend/src/components/**"
      - "packages/frontend/src/types/**"
      - "packages/frontend/src/assets/**"
      - "packages/backend/src/locales/**"
